sonar.projectKey=rikardronnkvist_ByteSift
sonar.organization=rikardronnkvist
sonar.projectName=ByteSift
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
